name: Messenger Bot 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

concurrency:
  group: messenger-bot
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Start Bot
        run: |
          echo "🚀 Starting Messenger Bot"

          while true
          do
            echo "▶️ Bot started at $(date)"

            timeout 345m node index.js

            echo "⚠️ Bot stopped or timeout reached"
            echo "🔄 Restarting bot in 5 seconds..."

            sleep 5
          done
